### ISSUE TITLE
PR Commenting bot doesn't work with forked repo's creating a PR

### ISSUE THREAD

**Issue by Baklap4** [oprypin/nightly.link#37]
Within Performous we're trying to use the PR Commenting. All works fine when the main repo creates a branch and opens a PR. However upon opening a PR from a forked repo branch into the main master we're getting the error: 

> [pr_comment](https://github.com/performous/performous/runs/6069687775?check_suite_focus=true)
This workflow doesn't match any pull requests!

These are the workflows within our master branch: https://github.com/performous/performous/tree/master/.github/workflows

**Comment by ooshlablu** [comment]
To add a bit more information:
`github.event.workflow_run.pull_requests` returns nothing when a PR is created from a fork, but returns everything you would expect when a PR is made internally to the repo. Unfortunately, I don't think there is really anything that can be done at the moment. This is either a bug in GitHub Actions or unsupported activity.
I have found a workaround using the issues search API. I will post a PR with my updates in a little while.

**Comment by oprypin** [comment]
Seeing as your PR changes to search API and this commit seems to change away from search API https://github.com/oprypin/nightly.link/commit/99348f45f0bad7dc54bff923a98bd8a901800e6c
-perhaps it's enough to revert it.
Could you please try the old version of the script and see if that works just as well as in your PR?

**Comment by oprypin** [comment]
Forgot to post the actual old version of the script that I mention. Here it is. https://github.com/oprypin/nightly.link/blob/4e83d1452dd1bf350ebe1a3910e395e6cf447fdf/.github/workflows/pr-comment.yml

**Comment by ooshlablu** [comment]
I tried the old version in my repo https://github.com/ooshlablu/performous
It failed with the error: `No matching pull request found`

**Comment by rfay** [comment]
I certainly have had this problem. Can it have anything to do with the recent update of actions/github-script to v6?

**Comment by oprypin** [comment]
You tell me ¯\\\_(ツ)_/¯
Just try the version before that https://github.com/oprypin/nightly.link/blob/4e83d1452dd1bf350ebe1a3910e395e6cf447fdf/.github/workflows/pr-comment.yml

**Comment by rfay** [comment]
Here's the version you suggest, working fine with a PR:

https://github.com/drud/junk-test-pr-comment/pull/2

**Comment by oprypin** [comment]
OK so in the meantime you can simply use that if it works better. There's no requirement that the script currently merged in the main branch here needs to be used, there are no permanent references to it.
I don't know when I'll get around to considering this issue.

**Comment by rfay** [comment]
In the test repo I did try out the new/current version just to verify; it fails as described here. But the old version, https://github.com/oprypin/nightly.link/blob/4e83d1452dd1bf350ebe1a3910e395e6cf447fdf/.github/workflows/pr-comment.yml works OK.

**Comment by white-gecko** [comment]
For me, just reverting to https://github.com/oprypin/nightly.link/blob/4e83d1452dd1bf350ebe1a3910e395e6cf447fdf/.github/workflows/pr-comment.yml did not work, I got:

```
…
TypeError: Cannot read properties of undefined (reading 'list')
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'list')
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:8:36)
    at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15143:16), <anonymous>:16:3)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15144:12)
    at main (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15236:26)
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15217:1
    at /home/runner/work/_actions/actions/github-script/v6/dist/index.js:15268:3
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:15271:12)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
```

did anyone find a stable solution that works with the current API?

**Comment by white-gecko** [comment]
This might be a working option: https://github.com/HarbourMasters/Shipwright/blob/071a2d0418d6fb7464a1ddccd2b647683da38eff/.github/workflows/pr-artifacts.yml

**Comment by white-gecko** [comment]
This one works for me now: https://github.com/AKSW/submission.d2r2.aksw.org/blob/680c23f975f51f06e6a4b7e212b56abfeca8f800/.github/workflows/pr-comment.yml
